<?php $this->extends('layout.phtml') ?>

<?php $this->begin('content') ?>

<iframe width="420" height="345" 
	src="https://www.youtube.com/embed/tgbNymZ7vqY">
</iframe>
<section class="completed">
	<h2>Your gear:</h2>
	<dl>
	<?php foreach ($domain->goals as $goal): ?>
		<?php if ($goal->hasAnswers() && (($answer = $goal->answer($state)) || $state->facts[$goal->name] != STATE_UNDEFINED)): ?>
			<dt><?=$state->substitute_variables($goal->description, ['Template', 'html'])?></dt>
			<dd><?php
				echo $answer
					? $state->substitute_variables($answer->description, ['Template', 'html'])
					: '<pre>' . $state->facts[$goal->name] . '</pre>';
				?></dd>
			<?php endif ?>
	<?php endforeach ?>
	</dl>
</section>
<?php $this->end() ?>
