<?php $this->extends('layout.phtml') ?>

<?php $this->begin('content') ?>
<section class="completed">
	<h2>Your gear:</h2>
	<dl>
	<?php foreach ($domain->goals as $goal): ?>
		<?php if ($goal->hasAnswers() && (($answer = $goal->answer($state)) || $state->facts[$goal->name] != STATE_UNDEFINED)): ?>
			<dt><?=$state->substitute_variables($goal->description, ['Template', 'html'])?></dt>
			<dd><?php
				echo $answer
					? $state->substitute_variables($answer->description, ['Template', 'html'])
					: '<pre>' . $state->facts[$goal->name] . '</pre>';
				?></dd>
			<?php endif ?>
	<?php endforeach ?>
	</dl>
</section>
	<div style="width:image width px; font-size:80%; text-align:left;">
		<a href="https://www.youtube.com/watch?v=JMROOeHbkps" target="_blank"><img src="https://www.kingofwatersports.com/images/products/cabrinha-2017-double-agent-foil/cabrinha-2017-double-agent-foil-alt1-zoom.jpg" 
				 alt="Hydrofoiling" width="350" style="padding-bottom:0.5em;" /></a>
	</div>
<?php $this->end() ?>
