<?php $this->extends('layout.phtml') ?>

<?php $this->begin('content') ?>
<section class="question">
	<img src="http://cdn.shopify.com/s/files/1/1892/3653/products/hydrofoil_1024x1024.jpg?v=1540117551" alt="Hydrofoiler" width="420">
	<p><?=$state->substitute_variables($question->description, ['Template', 'html'])?></p>

	<ol class="options">
		<?php foreach ($question->options as $option): ?>
		<li>
			<label>
				<input type="radio" name="answer" value="<?=_encode($option->consequences)?>">
				<?=$state->substitute_variables($option->description, ['Template', 'html'])?>
			</label>
		</li>
		<?php endforeach ?>
		<?php if($skippable): ?>
		<li class="skip-option">
			<label>
				<input type="radio" name="answer" value="<?=_encode(array())?>">
				I don't know
			</label>
		</li>
		<?php endif ?>
	</ol>
	<img src="http://cdn.shopify.com/s/files/1/1892/3653/products/hydrofoil_1024x1024.jpg?v=1540117551" alt="Hydrofoiler" width="420">
	<button type="submit">Continue…</button>
	
	
</section>
<?php $this->end() ?>
